
let storedBooks = [
    {
        title: 'Jewels of Nizam',
        author: 'Geeta Devi',
        publisher: '',
        paperback: '',
        isbn: '',
        summary: '',
        genre: '',
        posterURL: 'url(/images/book-0.jpg)',
        mostRecent: true,
        mostPopular: true,
        freeBook: true
    },
    {
        title: 'Cakes & Bakes',
        author: 'Sanjeev Kapoor',
        publisher: '',
        paperback: '',
        isbn: '',
        summary: '',
        genre: '',
        posterURL: 'url(/images/book-1.jpg)',
        mostRecent: true,
        mostPopular: true,
        freeBook: false
    },
    {
        title: 'Jamie\'s Kitchen',
        author: 'Jamie Oliver',
        publisher: '',
        paperback: '',
        isbn: '',
        summary: '',
        genre: '',
        posterURL: 'url(/images/book-2.jpg)',
        mostRecent: true,
        mostPopular: true,
        freeBook: false
    },
    {
        title: 'Inexpensive Family Meals',
        author: 'Simon Hoist',
        publisher: '',
        paperback: '',
        isbn: '',
        summary: '',
        genre: '',
        posterURL: 'url(/images/book-3.jpg)',
        mostRecent: true,
        mostPopular: false,
        freeBook: false
    },
    {
        title: 'Paleo Slow Cooking',
        author: 'Chrissy Gower',
        publisher: '',
        paperback: '',
        isbn: '',
        summary: '',
        genre: '',
        posterURL: 'url(/images/book-4.jpg)',
        mostRecent: true,
        mostPopular: false,
        freeBook: false
    },
    {
        title: 'Cook Like an Italian',
        author: 'Tobbie Puttock',
        publisher: '',
        paperback: '',
        isbn: '',
        summary: '',
        genre: '',
        posterURL: 'url(/images/book-5.jpg)',
        mostRecent: true,
        mostPopular: false,
        freeBook: false
    },
    {
        title: 'Suneeta Vaswani',
        author: 'Geeta Devi',
        publisher: '',
        paperback: '',
        isbn: '',
        summary: '',
        genre: '',
        posterURL: 'url(/images/book-6.jpg)',
        mostRecent: false,
        mostPopular: false,
        freeBook: false
    },
    {
        title: 'Jamie Does',
        author: 'Jamie Oliver',
        publisher: '',
        paperback: '',
        isbn: '',
        summary: '',
        genre: '',
        posterURL: 'url(/images/book-7.jpg)',
        mostRecent: false,
        mostPopular: false,
        freeBook: false
    },
    {
        title: 'Jamie\'s Italy',
        author: 'Jamie Oliver',
        publisher: '',
        paperback: '',
        isbn: '',
        summary: '',
        genre: '',
        posterURL: 'url(/images/book-8.jpg)',
        mostRecent: false,
        mostPopular: false,
        freeBook: false
    },
    {
        title: 'Vegetables Cookbook',
        author: 'Matthew Biggs',
        publisher: '',
        paperback: '',
        isbn: '',
        summary: '',
        genre: '',
        posterURL: 'url(/images/book-9.jpg)',
        mostRecent: false,
        mostPopular: false,
        freeBook: false
    }
];

export default storedBooks;